M48
; DRILL file KiCad 10.0.3 date 2026-06-19T01:48:54
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-19T01:48:54-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X106.567Y-72.167
X106.567Y-77.947
T2
X113.97Y-97.46
X115.24Y-49.2
X166.04Y-64.44
X166.04Y-92.38
M30
